version: "3"
volumes: 
  db-data:
services:
  nginx:
    image: nginx:stable-alpine
    container_name: crm-nginx
    ports:
      - 8000:80
    volumes:
      - ./api:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    container_name: crm-php
    build:
      context: ./api
    ports:
      - 9000:9000
    volumes:
      - ./api:/var/www/symfony_docker
    restart: on-failure
  database:
    platform: linux/x86_64
    container_name: crm-database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: symfony
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    container_name: crm-phpmyadmin
    depends_on: 
      - database
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: database